### ISSUE TITLE
Make sure availableCores() is fully agile to R CMD check 

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/parallelly#109]
`availableCores()` should return 2 whenever running `R CMD check`;

* It always respects `_R_CHECK_LIMIT_CORES_` which is set by `R CMD check --as-cran`
* The package sets `_R_CHECK_LIMIT_CORES_=TRUE` when loaded, if it detects that `R CMD check` is running

It uses an internal [queryRCmdCheck()](https://github.com/HenrikBengtsson/parallelly/blob/78a1b44021df2973d05224bfaa0b1a7abaf791ff/R/utils.R#L112-L164) function to query if `R CMD check` is running and what part of it.

Looking at `queryRCmdCheck()`, it might be the function does not pick up when checking package vignettes.

# Tasks

* [ ] Test what `availableCores()` return in vignettes.
* [ ] If not <= 2, then `queryRCmdCheck()` needs to be updated.

While at it:

* [ ] Validate that `availableCores()` returns <= 2 also when running via other test frameworks, e.g. **testthat**.

**Comment by HenrikBengtsson** [comment]
`availableCores()` return at most 2 whenever `R CMD check` is running, including when checking vignettes, because `R CMD check` sets ` _R_CHECK_LIMIT_CORES_`.
