### ISSUE TITLE
makeClusterPSOCK(): Add `default_packages`

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/parallelly#77]
Add argument `default_packages` to `makeClusterPSOCK()`, and start deprecating `methods`, which was there for R (< 3.5.0) purposes.

* [x] Support `default_packages = NULL`, which means that `--default-packages=...` is not passed to Rscript.
* [x] Otherwise, `default_packages` should take a character vector of package names.
* [x] Assert that `default_packages` are valid package names, cf. regular expression `.standard_regexps()$valid_package_name`
* [x] A value `"*"` should expand to the current value of `getOption("defaultPackages")`
* [x] ~~If running locally, we could validate that all default packages are installed, prior to launching the cluster nodes~~ Skip; adds unnecessary overhead
* [x] If `rscript[1]` is `Rscript`, then construct `--default-packages=...`
* [x] If `rscript[1]` is `R`/`Rterm`, then construct `R_DEFAULT_PACKAGES=...`, cf.  https://github.com/HenrikBengtsson/parallelly/issues/8#issuecomment-983265789
* [x] If `rscript[1]` is `R`/`Rterm`, then, if launching on MS Windows, call `R R_DEFAULT_PACKAGES="..." ...`, otherwise `R_DEFAULT_PACKAGES="..." R ...`, cf. https://github.com/HenrikBengtsson/Wishlist-for-R/issues/110
* [x] Figure out how to infer remote MS Windows workers ~~(or just assume they're Unix-like?)~~ Using `rscript_sh` to infer this, cf. https://github.com/HenrikBengtsson/parallelly/issues/8#issuecomment-995189085
